---
name: Cron actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # v5

        - name: HACS validation
          uses: "hacs/action@main"
          with:
            category: "integration"

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"
