---
name: Cron actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7

        - name: HACS validation
          uses: "hacs/action@main"
          with:
            category: "integration"

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"
